name: Submit a mod
description: Submit a mod to be added to the Sine marketplace.
title: "[add-theme]: "
labels: ["new-theme"]
body:
  - type: markdown
    attributes:
      value: |
        First time submitting a mod? The processs of adding mods to Sine is simple,
        all you have to do is add your homepage and we'll handle the rest!
        Just make sure your repository has a valid theme.json with an id, name, description, and other properties.
        You can find out more about these properties in the [Wiki](https://github.com/CosmoCreeper/Sine/wiki)
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: The URL of the theme's homepage or repository.
      placeholder: https://github.com/...
    validations:
      required: true
